### ISSUE TITLE
Data does not contain full stories

### ISSUE THREAD

**Issue by lilakk** [nyu-mll/SQuALITY#3]
Hi all, I noticed that some documents in the data file are not the full Project Gutenberg stories, for instance: the second story of the dev set ("Doorway to Kal-Jmar"). Are you aware of that issue? Is that intentional?

**Comment by lilakk** [comment]
I looked through the dev set, there are indices of stories that are not complete: 1, 2, 3, 5, 6, 7, 8, 9, 10, 12, 13, 15, 17, 19, 20, 21, 24

**Comment by yzpang** [comment]
Hi! Thanks for the issue. Do you mean that in dev set, for example, the article "Doorway to Kal-Jmar" ends with `That was that.` but in the actual story (https://www.gutenberg.org/files/63392/63392-h/63392-h.htm) there are many more paragraphs? 

This truncation is intentional (and happened in the QuALITY paper: https://arxiv.org/pdf/2112.08608.pdf), because we didn't want each article to be too long (might be too difficult for models & annotators might need to spend too much time on each task given that some Gutenberg stories are very very long). So for many articles, we only kept around 5k to 6k tokens (using `.split()` tokenization) -- we tried to make sure that the truncation point / stopping point is natural instead of in the middle of a paragraph. Unfortunately, that means many stories are incomplete. But the human-written summaries are also based on these truncated stories.

**Comment by lilakk** [comment]
Thanks for the clarification! But for "Doorway to Kal-Jmar", the truncated story doesn't include the part where Syme Rector is poisoned with xopa juice, or the part where the last doorway to Kal-Jmar closes forever. However, all 4 annotators mentioned these details in their summaries. Are you sure the human annotators weren't working on the original full story?

**Comment by yzpang** [comment]
Ah. Thanks for pointing this out. A few of us will investigate the issue today/tmrw and try to see how many inconsistencies there are, and we'll fix the data.

**Comment by lilakk** [comment]
Thanks!

**Comment by yzpang** [comment]
Update: Around 10 out of the 127 stories shouldn't be truncated. We're doing more investigation and we'll coordinate and hopefully fix this issue soon. Thanks again for noticing this!

**Comment by lilakk** [comment]
OK, thanks for the prompt response!
